version: '3.8'
services:
  app01:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo01
      - redis01
    environment:
      - MONGO_URI=mongodb://mongo01:27017/paqueteria
      - REDIS_HOST=redis01
      - REDIS_PORT=6379
      - PORT=3000
    networks:
      - red01

  mongo01:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - red01

  redis01:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - red01

networks:
  red01:
    driver: bridge
